---
apiVersion: spawn-eigr.io/v1
kind: ActorHost
metadata:
  name: spawn-springboot-example # Mandatory. Name of the Node containing Actor Host Functions
  namespace: default # Optional. Default namespace is "default"
  annotations:
    # Mandatory. Name of the ActorSystem declared in ActorSystem CRD
    spawn-eigr.io/actor-system: spawn-system

    # Optional. Default 9001
    spawn-eigr.io/sidecar-http-port: "9001"

    # Optional. Here I`m using Nats Broker without authentication
    spawn-eigr.io/sidecar-pubsub-adapter: "nats"
    spawn-eigr.io/sidecar-pubsub-nats-hosts: "nats://spawn-nats:4222"
    spawn-eigr.io/sidecar-image-tag: "docker.io/eigr/spawn-proxy:1.0.0-rc3-rc1"
spec:
  autoscaler:
    max: 3
  host:
    image: eigr/spawn-springboot-examples:0.5.3 # Mandatory
    ports:
      - name: http
        containerPort: 8090
    configuration:
      accessControlList:
        policies:
          - name: allow-all-from-same-actorsystem
            actors:
              - "*"
            type: allow
            fromActorSystems: # lista dos ActorSystem com permissao. Permitiria regras do tipo "*" tamb√©m
              - "spawn-system"
            actions:
              - "get"
              - "sum"
